language: python
python:
  - "3.3"
# command to install dependencies
install:
  # Install conda
  - sudo -H pip install conda
  # install deps
  - sudo conda init
  #- sudo conda update conda --yes
  - deps='pip numpy scipy nose scikit-image pillow coverage'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script:
  nosetests --with-coverage
after_success:
  coveralls
