language: python
python:
  - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install nose"
# command to run tests
script:
  coverage run rest.py
after_success:
  coveralls
